version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  demux2:
    lang: gstrust-http-template
    handler: ./demux2
    image: localhost:5000/demux2:latest
    environment:
      read_timeout: 15m
      exec_timeout: 15m
      write_timeout: 15m
    environment_file:
      - env.yaml

  split2:
    lang: gstpython-http-template
    handler: ./split2
    image: localhost:5000/split2:latest
    environment:
      read_timeout: 15m
      exec_timeout: 15m
      write_timeout: 15m
    environment_file:
      - env.yaml

  encode:
    lang: gstpython-http-template
    handler: ./encode
    image: localhost:5000/encode:latest
    environment:
      read_timeout: 15m
      exec_timeout: 15m
      write_timeout: 15m
    environment_file:
      - env.yaml

  stitch2:
    lang: gstpython-http-template
    handler: ./stitch2
    image: localhost:5000/stitch2:latest
    environment:
      read_timeout: 15m
      exec_timeout: 15m
      write_timeout: 15m
    environment_file:
      - env.yaml
    environment:
      GST_DEBUG: 3

  bento4:
    lang: bento4-python-debian
    handler: ./bento4
    image: localhost:5000/bento4:latest
    environment:
      read_timeout: 15m
      exec_timeout: 15m
      write_timeout: 15m
    environment_file:
      - env.yaml

